version: '3.7'
services:
  dogecoin:
    image: alexcj96/bitide-doge:latest
    ports:
      - 1337:1337
    networks:
      testing_net:
        ipv4_address: 172.16.238.11
    restart: always
    profiles: [lite,full]

  redis:
    image: redis
    volumes:
      - "./redis-data:/data"
    ports:
      - 6379:6379
    networks:
      testing_net:
        ipv4_address: 172.16.238.13
    restart: always
    profiles: [lite,full]

  rpc-server:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "rpc-server"
      - "--api-server-address=http://172.16.238.15:7777"
      - "--redis-uri=redis://172.16.238.13:6379/0"
    ports:
      - 3000:3000
    networks:
      testing_net:
        ipv4_address: 172.16.238.14
    restart: always
    depends_on:
      - redis
    profiles: [full]

  orchestrator:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "orchestrator"
      - "--bitcoin-rpc=http://devnet:devnet@172.16.238.11:1337/bitcoin-rpc/?network=dogeRegtest"
      - "--electrs-api=http://172.16.238.11:1337/api"
      - "--redis-uri=redis://172.16.238.13:6379/0"
    volumes:
      - "./db:/city-rollup/db"
    ports:
      - 7777:7777
    networks:
      testing_net:
        ipv4_address: 172.16.238.15
    restart: always
    depends_on:
      - redis
      - dogecoin
    profiles: [full]

  worker0:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "l2-worker"
      - "--redis-uri=redis://172.16.238.13:6379/0"
    volumes:
      - "/tmp:/tmp"
    networks:
      testing_net:
        ipv4_address: 172.16.238.16
    restart: always
    depends_on:
      - redis
    profiles: [full]

  worker1:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "l2-worker"
      - "--redis-uri=redis://172.16.238.13:6379/0"
    volumes:
      - "/tmp:/tmp"
    networks:
      testing_net:
        ipv4_address: 172.16.238.17
    restart: always
    depends_on:
      - redis
    profiles: [full]

  worker2:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      - "l2-worker"
      - "--redis-uri=redis://172.16.238.13:6379/0"
    volumes:
      - "/tmp:/tmp"
    networks:
      testing_net:
        ipv4_address: 172.16.238.18
    restart: always
    depends_on:
      - redis
    profiles: [full]

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
